name: DanMar1492

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick passing check
        run: |
          echo "Running required check: DanMar1492"
          exit 0
